AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stock Analysis Project

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:
  ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stock_analysis/
      Handler: api.handler.lambda_handler
      Runtime: python3.9
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: GET
        StaticFiles:
          Type: Api
          Properties:
            Path: /static/{proxy+}
            Method: GET
        StockApi:
          Type: Api
          Properties:
            Path: /api/stocks
            Method: GET