AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stock Analysis Project - A serverless application for analyzing stock data.

Globals:
  Function:
    Timeout: 10

Resources:
  DataCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stock_analysis/collectors/
      Handler: data_collection.lambda_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          LOG_LEVEL: INFO

  ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stock_analysis/api/
      Handler: handler.lambda_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          LOG_LEVEL: INFO

Outputs:
  DataCollectionFunction:
    Description: "ARN of the Data Collection Lambda Function"
    Value: !GetAtt DataCollectionFunction.Arn

  ApiHandlerFunction:
    Description: "ARN of the API Handler Lambda Function"
    Value: !GetAtt ApiHandlerFunction.Arn